INCLUDE "constants.h.asm"

TRACK_ADDR = &8000
IF EMBED_TRACK_INLINE = FALSE AND USE_SWRAM AND DISK2_PARTS > 0
    FOR n, DISK0_PARTS, DISK0_PARTS + DISK2_PARTS - 1
        PUTFILE TRACK_SRC_FILENAME_PREFIX + RIGHT$("00" + STR$(n), 2), TRACK_DST_FILENAME_PREFIX + RIGHT$("00" + STR$(n), 2), TRACK_ADDR
    NEXT
ENDIF